name: make-it-black

description: Action to run black on python files and commit

inputs:
  python-version:
    description: 'Python Version'
    required: false
    default: '3.11'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Check ref
      run: |
        echo "Checking ref"
        git rev-parse HEAD
      shell: bash
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install-black
      run: pip install --upgrade black
      shell: bash
    - name: Run Black
      run: black .
      shell: bash
    - name: Check Status
      run: |
        git status
      shell: bash
