name: make-it-black

description: Action to run black on python files and commit

inputs:
  TestInput:
    description: 'Test Input'
    required: True

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Check ref
      run: |
        echo "Checking ref"
        git rev-parse HEAD
    - run: echo "${{ inputs.TestInput }}"
      shell: bash
